# Generated by Django 2.2.1 on 2019-05-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanNationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_nationality', models.CharField(max_length=100)),
                ('cleaned_nationality', models.CharField(max_length=100)),
                ('score', models.FloatField(blank=True)),
            ],
        ),
    ]
