# Generated by Django 2.2.1 on 2019-05-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NationalityClean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerUserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=100)),
                ('score', models.FloatField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cleannationality',
            name='score',
            field=models.FloatField(),
        ),
    ]
