# Generated by Django 2.2.1 on 2019-05-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NationalityClean', '0003_auto_20190507_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleannationality',
            name='score',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
    ]
