# Generated by Django 2.2.1 on 2019-05-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NationalityClean', '0004_auto_20190515_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleannationality',
            name='score',
            field=models.FloatField(),
        ),
    ]
