# Generated by Django 2.2.1 on 2019-05-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NationalityClean', '0005_auto_20190515_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleannationality',
            name='correct_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cleannationality',
            name='score',
            field=models.DecimalField(decimal_places=17, max_digits=17),
        ),
    ]
