# Generated by Django 2.2.1 on 2019-05-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NationalityClean', '0006_auto_20190515_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleannationality',
            name='correct_status',
        ),
        migrations.AlterField(
            model_name='cleannationality',
            name='score',
            field=models.FloatField(),
        ),
    ]
