# Generated by Django 2.2.1 on 2019-05-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NationalityClean', '0007_auto_20190515_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterNationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unverified_nationality', models.CharField(max_length=100)),
                ('verified_nationality', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('input_data', models.CharField(max_length=100)),
            ],
        ),
    ]
