# Generated by Django 2.2.1 on 2019-05-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NationalityClean', '0008_filternationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filternationality',
            name='input_data',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
