# Generated by Django 2.2.1 on 2019-05-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NationalityClean', '0010_auto_20190515_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CleanNationality',
        ),
    ]
