# Generated by Django 2.2.1 on 2019-05-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NationalityClean', '0011_delete_cleannationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekeruserdetail',
            name='score',
        ),
        migrations.AlterUniqueTogether(
            name='filternationality',
            unique_together={('unverified_nationality', 'verified_nationality')},
        ),
    ]
